---
  - name: Installing Gunicorn
    yum:
      name: python36u-gunicorn

  - name: Creating systemd unit files for services
    template:
      src: "{{ item }}.service.j2"
      dest: /etc/systemd/system/{{ item }}.service
    with_items: "{{ kartel_services }}"

#  - name: Update systemd configuration
#    command: systemctl daemon-reload

  - name: Creating systemd temporary directory configuration for Gunicorn PID files
    copy:
      content: d /run/gunicorn 0755 gunicorn gunicorn -
      dest: /etc/tmpfiles.d/gunicorn.conf

  - name: Crating the directory itself
    command: systemd-tmpfiles --create

  - name: Creating directories for log files
    file:
      path: /var/log/kartel/{{ item }}
      group: gunicorn
      owner: gunicorn
      mode: 0755
      state: directory
    with_items: "{{ kartel_services }}"

  - name: Creating logrotate configuration for services
    copy:
      src: kartel
      dest: /etc/logrotate.d/kartel

 # - name: Install requirements for services
 #   shell: pip3.6 install -r /opt/kartel/services/{{ item }}/requirements.txt
 #   with_items: "{{ kartel_services }}"

 # - name: Stopping services in case of version change
 #   service:
 #     name: "{{ item }}"
 #     state: stopped
 #   with_items: "{{ kartel_services }}"
 #   ignore_errors: yes

 # - name: Ensure that services are enabled and started
 #   service:
 #     name: "{{ item }}"
 #     enabled: yes
 #     state: started
 #   with_items: "{{ kartel_services }}"
